INSERT INTO currency (id, code, currency_code, rate_to_kzt) VALUES
                                                                (4, 'GBP', 'British Pound', 610),
                                                                (5, 'RUB', 'Russian Ruble', 5.4),
                                                                (6, 'CNY', 'Chinese Yuan', 70),
                                                                (7, 'JPY', 'Japanese Yen', 3.3),
                                                                (8, 'TRY', 'Turkish Lira', 18.5),
                                                                (9, 'AED', 'UAE Dirham', 136),
                                                                (10, 'CHF', 'Swiss Franc', 560),
                                                                (11, 'INR', 'Indian Rupee', 6.1),
                                                                (12, 'CAD', 'Canadian Dollar', 370),
                                                                (13, 'AUD', 'Australian Dollar', 330),
                                                                (14, 'SEK', 'Swedish Krona', 46),
                                                                (15, 'NOK', 'Norwegian Krone', 44),
                                                                (16, 'DKK', 'Danish Krone', 71),
                                                                (17, 'PLN', 'Polish Zloty', 123),
                                                                (18, 'CZK', 'Czech Koruna', 21),
                                                                (19, 'HUF', 'Hungarian Forint', 1.4),
                                                                (20, 'UZS', 'Uzbek Sum', 0.04),
                                                                (21, 'KGS', 'Kyrgyz Som', 5.6),
                                                                (22, 'TJS', 'Tajik Somoni', 45),
                                                                (23, 'AZN', 'Azerbaijani Manat', 295),
                                                                (24, 'AMD', 'Armenian Dram', 1.25),
                                                                (25, 'BYN', 'Belarusian Ruble', 150),
                                                                (26, 'GEL', 'Georgian Lari', 190),
                                                                (27, 'UAH', 'Ukrainian Hryvnia', 13.5),
                                                                (28, 'MDL', 'Moldovan Leu', 28),
                                                                (29, 'RON', 'Romanian Leu', 106),
                                                                (30, 'BGN', 'Bulgarian Lev', 270),
                                                                (31, 'HRK', 'Croatian Kuna', 70),
                                                                (32, 'RSD', 'Serbian Dinar', 4.6),
                                                                (33, 'ILS', 'Israeli Shekel', 135),
                                                                (34, 'SAR', 'Saudi Riyal', 133),
                                                                (35, 'QAR', 'Qatari Riyal', 137),
                                                                (36, 'KWD', 'Kuwaiti Dinar', 1630),
                                                                (37, 'BHD', 'Bahraini Dinar', 1320),
                                                                (38, 'OMR', 'Omani Rial', 1290),
                                                                (39, 'PKR', 'Pakistani Rupee', 1.8),
                                                                (40, 'BDT', 'Bangladeshi Taka', 4.4),
                                                                (41, 'THB', 'Thai Baht', 14),
                                                                (42, 'SGD', 'Singapore Dollar', 370),
                                                                (43, 'HKD', 'Hong Kong Dollar', 64),
                                                                (44, 'MYR', 'Malaysian Ringgit', 110),
                                                                (45, 'VND', 'Vietnamese Dong', 0.021),
                                                                (46, 'IDR', 'Indonesian Rupiah', 0.032),
                                                                (47, 'PHP', 'Philippine Peso', 9),
                                                                (48, 'LKR', 'Sri Lankan Rupee', 1.6),
                                                                (49, 'KHR', 'Cambodian Riel', 0.12),
                                                                (50, 'MMK', 'Myanmar Kyat', 0.24),
                                                                (51, 'LAK', 'Lao Kip', 0.023),
                                                                (52, 'BRL', 'Brazilian Real', 102),
                                                                (53, 'ARS', 'Argentine Peso', 0.6),
                                                                (54, 'CLP', 'Chilean Peso', 0.52),
                                                                (55, 'COP', 'Colombian Peso', 0.12),
                                                                (56, 'MXN', 'Mexican Peso', 29),
                                                                (57, 'PEN', 'Peruvian Sol', 130),
                                                                (58, 'UYU', 'Uruguayan Peso', 12),
                                                                (59, 'PYG', 'Paraguayan Guarani', 0.067),
                                                                (60, 'VEF', 'Venezuelan Bolivar', 0.016),
                                                                (61, 'ZAR', 'South African Rand', 28),
                                                                (62, 'EGP', 'Egyptian Pound', 10.5),
                                                                (63, 'NGN', 'Nigerian Naira', 0.32),
                                                                (64, 'KES', 'Kenyan Shilling', 3.8),
                                                                (65, 'TZS', 'Tanzanian Shilling', 0.19),
                                                                (66, 'UGX', 'Ugandan Shilling', 0.14),
                                                                (67, 'MAD', 'Moroccan Dirham', 49),
                                                                (68, 'DZD', 'Algerian Dinar', 3.7),
                                                                (69, 'TND', 'Tunisian Dinar', 162),
                                                                (70, 'ETB', 'Ethiopian Birr', 8.9),
                                                                (71, 'GHS', 'Ghanaian Cedi', 35),
                                                                (72, 'XOF', 'West African CFA Franc', 0.8),
                                                                (73, 'XAF', 'Central African CFA Franc', 0.8),
                                                                (74, 'MGA', 'Malagasy Ariary', 0.11),
                                                                (75, 'ZMW', 'Zambian Kwacha', 21),
                                                                (76, 'MWK', 'Malawian Kwacha', 0.29),
                                                                (77, 'MZN', 'Mozambican Metical', 7.7),
                                                                (78, 'BWP', 'Botswana Pula', 37),
                                                                (79, 'SZL', 'Swazi Lilangeni', 28),
                                                                (80, 'NAD', 'Namibian Dollar', 28),
                                                                (81, 'ISK', 'Icelandic Krona', 3.5),
                                                                (82, 'EEK', 'Estonian Kroon', 33),
                                                                (83, 'LTL', 'Lithuanian Litas', 150),
                                                                (84, 'LVL', 'Latvian Lats', 830),
                                                                (85, 'MKD', 'Macedonian Denar', 8.6),
                                                                (86, 'ALL', 'Albanian Lek', 5.4),
                                                                (87, 'SYP', 'Syrian Pound', 0.2),
                                                                (88, 'IQD', 'Iraqi Dinar', 0.38),
                                                                (89, 'IRR', 'Iranian Rial', 0.012),
                                                                (90, 'AFN', 'Afghan Afghani', 7.6),
                                                                (91, 'NPR', 'Nepalese Rupee', 3.9),
                                                                (92, 'MVR', 'Maldivian Rufiyaa', 33),
                                                                (93, 'BND', 'Brunei Dollar', 370),
                                                                (94, 'FJD', 'Fijian Dollar', 230),
                                                                (95, 'PGK', 'Papua New Guinean Kina', 140),
                                                                (96, 'WST', 'Samoan Tala', 180),
                                                                (97, 'TOP', 'Tongan Paʻanga', 200),
                                                                (98, 'NZD', 'New Zealand Dollar', 310),
                                                                (99, 'BSD', 'Bahamian Dollar', 500),
                                                                (100, 'JMD', 'Jamaican Dollar', 3.2);
